/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package calculadorajarda;

import java.awt.Color;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author felipe.silva
 */
public class CalcularJardaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CalcularJardaJFrame
     */
    public CalcularJardaJFrame() {
       this.getContentPane().setBackground(new java.awt.Color(255, 255, 204));
        
        initComponents();
        txtJarda1.setDocument(new OnlyNum());
        txtMetro1.setDocument(new OnlyNum());
        btnCalcular.setEnabled(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup5 = new javax.swing.ButtonGroup();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtJarda1 = new javax.swing.JTextField();
        txtMetro1 = new javax.swing.JTextField();
        btnCalcular = new javax.swing.JButton();
        RadioBtnYdToM = new javax.swing.JRadioButton();
        RadioBtnMToYd = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(255, 255, 204));
        setResizable(false);
        setType(java.awt.Window.Type.UTILITY);

        jLabel2.setText("Jarda (yd)");

        jLabel3.setText("Metro (m)");

        txtJarda1.setEnabled(false);
        txtJarda1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJarda1ActionPerformed(evt);
            }
        });

        txtMetro1.setEnabled(false);

        btnCalcular.setText("Calcular");
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });

        buttonGroup5.add(RadioBtnYdToM);
        RadioBtnYdToM.setText("Converter Jarda para Metros");
        RadioBtnYdToM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtnYdToMActionPerformed(evt);
            }
        });

        buttonGroup5.add(RadioBtnMToYd);
        RadioBtnMToYd.setText("Converter Metros para Jarda");
        RadioBtnMToYd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RadioBtnMToYdActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/calculadorajarda/logo.png"))); // NOI18N
        jLabel4.setText("jLabel4");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RadioBtnMToYd)
                            .addComponent(RadioBtnYdToM)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtJarda1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioBtnYdToM)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RadioBtnMToYd)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtJarda1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtMetro1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addComponent(btnCalcular, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        double jarda;
        double metro;
        double conversaoMetro;
        double conversaoJarda;
        
        
        
        
     if(!this.txtJarda1.getText().equals("") || !this.txtMetro1.getText().equals("")){
        if (RadioBtnYdToM.isSelected()){
        
         
         jarda=Double.parseDouble(txtJarda1.getText());
         conversaoJarda= jarda*0.9144;
         String msg = String.format("Resultado em Metros =  %.2f %n ", conversaoJarda);
         JOptionPane.showMessageDialog(null, msg);
        }
        else{
         
        
         metro=Double.parseDouble(txtMetro1.getText());
         conversaoMetro= metro/0.9144;
         String msg = String.format("Resultado em Jardas =  %.2f %n ", conversaoMetro);
         JOptionPane.showMessageDialog(null,msg);
         
        }
     }else{
         JOptionPane.showMessageDialog(null,"Digite um valor valido!");
     
     
     }
        
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void RadioBtnYdToMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtnYdToMActionPerformed
       txtMetro1.setText("");
       txtMetro1.setEnabled(false);
       txtJarda1.setEnabled(true);
       btnCalcular.setEnabled(true);
            
    }//GEN-LAST:event_RadioBtnYdToMActionPerformed

    private void RadioBtnMToYdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RadioBtnMToYdActionPerformed
        txtJarda1.setText(""); 
        txtJarda1.setEnabled(false);
        txtMetro1.setEnabled(true);
        btnCalcular.setEnabled(true);
    }//GEN-LAST:event_RadioBtnMToYdActionPerformed

    private void txtJarda1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJarda1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJarda1ActionPerformed
  
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalcularJardaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalcularJardaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalcularJardaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalcularJardaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalcularJardaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton RadioBtnMToYd;
    private javax.swing.JRadioButton RadioBtnYdToM;
    private javax.swing.JButton btnCalcular;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txtJarda1;
    private javax.swing.JTextField txtMetro1;
    // End of variables declaration//GEN-END:variables
    
}

